/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Auto-generated code. Do not edit.

package com.google.genai.kotlin.types

import kotlin.jvm.JvmInline
import kotlinx.serialization.Serializable

/** Delivery mode for the generated content. */
@Serializable
@JvmInline
value class Delivery(val value: String) {
  companion object {

    /** Default value. This value is unused. */
    val DELIVERY_UNSPECIFIED = Delivery("DELIVERY_UNSPECIFIED")

    /** Generated bytes are returned inline in the response. */
    val INLINE = Delivery("INLINE")

    /** Generated content is stored and a URI is returned. */
    val URI = Delivery("URI")
  }
}
