/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Auto-generated code. Do not edit.

package com.google.genai.kotlin.types

import kotlinx.serialization.Serializable

/**
 * Code generated by the model that is meant to be executed, and the result returned to the model.
 * Generated when using the `CodeExecution` tool, in which the code will be automatically executed,
 * and a corresponding CodeExecutionResult will also be generated.
 */
@Serializable
data class ExecutableCode(

  /** Required. The code to be executed. */
  val code: String? = null,

  /** Required. Programming language of the `code`. */
  val language: Language? = null,

  /**
   * Optional. Unique identifier of the `ExecutableCode` part. The server returns the
   * `CodeExecutionResult` with the matching `id`. This field is not supported in Vertex AI.
   */
  val id: String? = null,
)
