/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Auto-generated code. Do not edit.

package com.google.genai.kotlin.types

import kotlin.jvm.JvmInline
import kotlinx.serialization.Serializable

/**
 * Output only. The reason why the model stopped generating tokens.
 *
 * If empty, the model has not stopped generating the tokens.
 */
@Serializable
@JvmInline
value class FinishReason(val value: String) {
  override fun toString(): String = value

  companion object {

    /** The finish reason is unspecified. */
    val FINISH_REASON_UNSPECIFIED = FinishReason("FINISH_REASON_UNSPECIFIED")

    /** The model reached a natural stopping point or a configured stop sequence. */
    val STOP = FinishReason("STOP")

    /**
     * The model generated the maximum number of tokens allowed by the `max_output_tokens`
     * parameter.
     */
    val MAX_TOKENS = FinishReason("MAX_TOKENS")

    /**
     * The model stopped generating because the content potentially violates safety policies. NOTE:
     * When streaming, the `content` field is empty if content filters block the output.
     */
    val SAFETY = FinishReason("SAFETY")

    /** The model stopped generating because the content may be a recitation from a source. */
    val RECITATION = FinishReason("RECITATION")

    /**
     * The response candidate content was flagged for using an unsupported language. This enum value
     * is not supported in Vertex AI.
     */
    val LANGUAGE = FinishReason("LANGUAGE")

    /** The model stopped generating for a reason not otherwise specified. */
    val OTHER = FinishReason("OTHER")

    /**
     * The model stopped generating because the content contains a term from a configured blocklist.
     */
    val BLOCKLIST = FinishReason("BLOCKLIST")

    /** The model stopped generating because the content may be prohibited. */
    val PROHIBITED_CONTENT = FinishReason("PROHIBITED_CONTENT")

    /**
     * The model stopped generating because the content may contain sensitive personally
     * identifiable information (SPII).
     */
    val SPII = FinishReason("SPII")

    /** The model generated a function call that is syntactically invalid and can't be parsed. */
    val MALFORMED_FUNCTION_CALL = FinishReason("MALFORMED_FUNCTION_CALL")

    /** Token generation stopped because generated images have safety violations. */
    val IMAGE_SAFETY = FinishReason("IMAGE_SAFETY")

    /** The generated image may contain prohibited content. */
    val IMAGE_PROHIBITED_CONTENT = FinishReason("IMAGE_PROHIBITED_CONTENT")

    /** The image generation stopped for a reason not otherwise specified. */
    val IMAGE_OTHER = FinishReason("IMAGE_OTHER")

    /** The model was expected to generate an image, but didn't. */
    val NO_IMAGE = FinishReason("NO_IMAGE")

    /** The generated image may be a recitation from a source. */
    val IMAGE_RECITATION = FinishReason("IMAGE_RECITATION")

    /** The tool call generated by the model is invalid. */
    val UNEXPECTED_TOOL_CALL = FinishReason("UNEXPECTED_TOOL_CALL")

    /** Model called too many tools consecutively, thus the system exited execution. */
    val TOO_MANY_TOOL_CALLS = FinishReason("TOO_MANY_TOOL_CALLS")

    /**
     * Request has at least one thought signature missing. This enum value is not supported in
     * Vertex AI.
     */
    val MISSING_THOUGHT_SIGNATURE = FinishReason("MISSING_THOUGHT_SIGNATURE")

    /** Finished due to malformed response. This enum value is not supported in Vertex AI. */
    val MALFORMED_RESPONSE = FinishReason("MALFORMED_RESPONSE")

    /**
     * Request was filtered by an escalation rule. This enum value is not supported in Vertex AI.
     */
    val ESCALATION = FinishReason("ESCALATION")

    /**
     * Indicates that token generation stopped because the user account is limited or disabled due
     * to Prohibited Use Policy (PUP) violations. This enum value is not supported in Vertex AI.
     */
    val PUP_LIMITED_DISABLED = FinishReason("PUP_LIMITED_DISABLED")

    /**
     * The model response was blocked by Model Armor. This enum value is not supported in Gemini
     * API.
     */
    val MODEL_ARMOR = FinishReason("MODEL_ARMOR")
  }
}
