/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Auto-generated code. Do not edit.

package com.google.genai.kotlin.types

import kotlin.jvm.JvmInline
import kotlinx.serialization.Serializable

/**
 * Output only. The reason why the model stopped generating tokens.
 *
 * If empty, the model has not stopped generating the tokens.
 */
@Serializable
@JvmInline
value class FinishReason(val value: String) {
  companion object {

    /** The finish reason is unspecified. */
    val FINISH_REASON_UNSPECIFIED = FinishReason("FINISH_REASON_UNSPECIFIED")

    /** Token generation reached a natural stopping point or a configured stop sequence. */
    val STOP = FinishReason("STOP")

    /** Token generation reached the configured maximum output tokens. */
    val MAX_TOKENS = FinishReason("MAX_TOKENS")

    /**
     * Token generation stopped because the content potentially contains safety violations. NOTE:
     * When streaming, [content][] is empty if content filters blocks the output.
     */
    val SAFETY = FinishReason("SAFETY")

    /** The token generation stopped because of potential recitation. */
    val RECITATION = FinishReason("RECITATION")

    /** The token generation stopped because of using an unsupported language. */
    val LANGUAGE = FinishReason("LANGUAGE")

    /** All other reasons that stopped the token generation. */
    val OTHER = FinishReason("OTHER")

    /** Token generation stopped because the content contains forbidden terms. */
    val BLOCKLIST = FinishReason("BLOCKLIST")

    /** Token generation stopped for potentially containing prohibited content. */
    val PROHIBITED_CONTENT = FinishReason("PROHIBITED_CONTENT")

    /**
     * Token generation stopped because the content potentially contains Sensitive Personally
     * Identifiable Information (SPII).
     */
    val SPII = FinishReason("SPII")

    /** The function call generated by the model is invalid. */
    val MALFORMED_FUNCTION_CALL = FinishReason("MALFORMED_FUNCTION_CALL")

    /** Token generation stopped because generated images have safety violations. */
    val IMAGE_SAFETY = FinishReason("IMAGE_SAFETY")

    /** The tool call generated by the model is invalid. */
    val UNEXPECTED_TOOL_CALL = FinishReason("UNEXPECTED_TOOL_CALL")

    /** Image generation stopped because the generated images have prohibited content. */
    val IMAGE_PROHIBITED_CONTENT = FinishReason("IMAGE_PROHIBITED_CONTENT")

    /** The model was expected to generate an image, but none was generated. */
    val NO_IMAGE = FinishReason("NO_IMAGE")

    /** Image generation stopped because the generated image may be a recitation from a source. */
    val IMAGE_RECITATION = FinishReason("IMAGE_RECITATION")

    /** Image generation stopped for a reason not otherwise specified. */
    val IMAGE_OTHER = FinishReason("IMAGE_OTHER")
  }
}
