/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Auto-generated code. Do not edit.

package com.google.genai.kotlin.types

import kotlinx.serialization.Serializable

/**
 * Incremental server update generated by the model in response to client messages.
 *
 * Content is generated as quickly as possible, and not in real time. Clients may choose to buffer
 * and play it out in real time.
 */
@Serializable
data class LiveServerContent(

  /** The content that the model has generated as part of the current conversation with the user. */
  val modelTurn: Content? = null,

  /**
   * If true, indicates that the model is done generating. Generation will only start in response to
   * additional client messages. Can be set alongside `content`, indicating that the `content` is
   * the last in the turn.
   */
  val turnComplete: Boolean? = null,

  /**
   * If true, indicates that a client message has interrupted current model generation. If the
   * client is playing out the content in realtime, this is a good signal to stop and empty the
   * current queue.
   */
  val interrupted: Boolean? = null,

  /** Metadata returned to client when grounding is enabled. */
  val groundingMetadata: GroundingMetadata? = null,

  /**
   * If true, indicates that the model is done generating. When model is interrupted while
   * generating there will be no generation_complete message in interrupted turn, it will go through
   * interrupted > turn_complete. When model assumes realtime playback there will be delay between
   * generation_complete and turn_complete that is caused by model waiting for playback to finish.
   * If true, indicates that the model has finished generating all content. This is a signal to the
   * client that it can stop sending messages.
   */
  val generationComplete: Boolean? = null,

  /**
   * Input transcription. The transcription is independent to the model turn which means it doesn’t
   * imply any ordering between transcription and model turn.
   */
  val inputTranscription: Transcription? = null,

  /**
   * Output transcription. The transcription is independent to the model turn which means it doesn’t
   * imply any ordering between transcription and model turn.
   */
  val outputTranscription: Transcription? = null,

  /** Metadata related to url context retrieval tool. */
  val urlContextMetadata: UrlContextMetadata? = null,

  /** Reason for the turn is complete. */
  val turnCompleteReason: TurnCompleteReason? = null,

  /**
   * If true, indicates that the model is not generating content because it is waiting for more
   * input from the user, e.g. because it expects the user to continue talking.
   */
  val waitingForInput: Boolean? = null,

  /** Low latency transcription updated while the user is speaking. */
  val interimInputTranscription: Transcription? = null,
)
