/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Auto-generated code. Do not edit.

package com.google.genai.kotlin.types

import kotlinx.serialization.Serializable

/** Response message for API call. */
@Serializable
data class LiveServerMessage(

  /** Sent in response to a `LiveClientSetup` message from the client. */
  val setupComplete: LiveServerSetupComplete? = null,

  /** Content generated by the model in response to client messages. */
  val serverContent: LiveServerContent? = null,

  /**
   * Request for the client to execute the `function_calls` and return the responses with the
   * matching `id`s.
   */
  val toolCall: LiveServerToolCall? = null,

  /**
   * Notification for the client that a previously issued `ToolCallMessage` with the specified `id`s
   * should have been not executed and should be cancelled.
   */
  val toolCallCancellation: LiveServerToolCallCancellation? = null,

  /** Usage metadata about model response(s). */
  val usageMetadata: UsageMetadata? = null,

  /** Server will disconnect soon. */
  val goAway: LiveServerGoAway? = null,

  /** Update of the session resumption state. */
  val sessionResumptionUpdate: LiveServerSessionResumptionUpdate? = null,

  /** Voice activity detection signal. Allowlisted only. */
  val voiceActivityDetectionSignal: VoiceActivityDetectionSignal? = null,

  /** Voice activity signal. */
  val voiceActivity: VoiceActivity? = null,
)
