/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Auto-generated code. Do not edit.

package com.google.genai.kotlin.types

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * A datatype containing media content.
 *
 * Exactly one field within a Part should be set, representing the specific type of content being
 * conveyed. Using multiple fields within the same `Part` instance is considered invalid.
 */
@Serializable
data class Part(

  /** Media resolution for the input media. */
  val mediaResolution: PartMediaResolution? = null,

  /** Optional. The result of executing the ExecutableCode. */
  val codeExecutionResult: CodeExecutionResult? = null,

  /** Optional. Code generated by the model that is intended to be executed. */
  val executableCode: ExecutableCode? = null,

  /**
   * Optional. The URI-based data of the part. This can be used to include files from Google Cloud
   * Storage.
   */
  val fileData: FileData? = null,

  /**
   * Optional. A predicted function call returned from the model. This contains the name of the
   * function to call and the arguments to pass to the function.
   */
  val functionCall: FunctionCall? = null,

  /**
   * Optional. The result of a function call. This is used to provide the model with the result of a
   * function call that it predicted.
   */
  val functionResponse: FunctionResponse? = null,

  /**
   * Optional. The inline data content of the part. This can be used to include images, audio, or
   * video in a request.
   */
  val inlineData: Blob? = null,

  /**
   * Optional. The text content of the part. When sent from the VSCode Gemini Code Assist extension,
   * references to @mentioned items will be converted to markdown boldface text. For example
   * `@my-repo` will be converted to and sent as `**my-repo**` by the IDE agent.
   */
  val text: String? = null,

  /** Optional. Indicates whether the `part` represents the model's thought process or reasoning. */
  val thought: Boolean? = null,

  /** Optional. An opaque signature for the thought so it can be reused in subsequent requests. */
  @Serializable(with = ByteArrayAsBase64Serializer::class) val thoughtSignature: ByteArray? = null,

  /**
   * Optional. Video metadata. The metadata should only be specified while the video data is
   * presented in inline_data or file_data.
   */
  val videoMetadata: VideoMetadata? = null,

  /**
   * Server-side tool call. This field is populated when the model predicts a tool invocation that
   * should be executed on the server. The client is expected to echo this message back to the API.
   */
  val toolCall: ToolCall? = null,

  /**
   * The output from a server-side ToolCall execution. This field is populated by the client with
   * the results of executing the corresponding ToolCall.
   */
  val toolResponse: ToolResponse? = null,

  /**
   * Custom metadata associated with the Part. Agents using genai.Part as content representation may
   * need to keep track of the additional information. For example it can be name of a file/source
   * from which the Part originates or a way to multiplex multiple Part streams. This field is not
   * supported in Vertex AI.
   */
  val partMetadata: Map<String, JsonElement>? = null,

  /** Output only. The transcription of the audio part. */
  val audioTranscription: Transcription? = null,
)
