/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Auto-generated code. Do not edit.

package com.google.genai.kotlin.types

import kotlin.jvm.JvmInline
import kotlinx.serialization.Serializable

/** The reason why the turn is complete. */
@Serializable
@JvmInline
value class TurnCompleteReason(val value: String) {
  companion object {

    /** Default value. Reason is unspecified. */
    val TURN_COMPLETE_REASON_UNSPECIFIED = TurnCompleteReason("TURN_COMPLETE_REASON_UNSPECIFIED")

    /** The function call generated by the model is invalid. */
    val MALFORMED_FUNCTION_CALL = TurnCompleteReason("MALFORMED_FUNCTION_CALL")

    /** The response is rejected by the model. */
    val RESPONSE_REJECTED = TurnCompleteReason("RESPONSE_REJECTED")

    /** Needs more input from the user. */
    val NEED_MORE_INPUT = TurnCompleteReason("NEED_MORE_INPUT")

    /** Input content is prohibited. */
    val PROHIBITED_INPUT_CONTENT = TurnCompleteReason("PROHIBITED_INPUT_CONTENT")

    /** Input image contains prohibited content. */
    val IMAGE_PROHIBITED_INPUT_CONTENT = TurnCompleteReason("IMAGE_PROHIBITED_INPUT_CONTENT")

    /** Input text contains prominent person reference. */
    val INPUT_TEXT_CONTAIN_PROMINENT_PERSON_PROHIBITED =
      TurnCompleteReason("INPUT_TEXT_CONTAIN_PROMINENT_PERSON_PROHIBITED")

    /** Input image contains celebrity. */
    val INPUT_IMAGE_CELEBRITY = TurnCompleteReason("INPUT_IMAGE_CELEBRITY")

    /** Input image contains photo realistic child. */
    val INPUT_IMAGE_PHOTO_REALISTIC_CHILD_PROHIBITED =
      TurnCompleteReason("INPUT_IMAGE_PHOTO_REALISTIC_CHILD_PROHIBITED")

    /** Input text contains NCII content. */
    val INPUT_TEXT_NCII_PROHIBITED = TurnCompleteReason("INPUT_TEXT_NCII_PROHIBITED")

    /** Other input safety issue. */
    val INPUT_OTHER = TurnCompleteReason("INPUT_OTHER")

    /** Input contains IP violation. */
    val INPUT_IP_PROHIBITED = TurnCompleteReason("INPUT_IP_PROHIBITED")

    /** Input matched blocklist. */
    val BLOCKLIST = TurnCompleteReason("BLOCKLIST")

    /** Input is unsafe for image generation. */
    val UNSAFE_PROMPT_FOR_IMAGE_GENERATION =
      TurnCompleteReason("UNSAFE_PROMPT_FOR_IMAGE_GENERATION")

    /** Generated image failed safety check. */
    val GENERATED_IMAGE_SAFETY = TurnCompleteReason("GENERATED_IMAGE_SAFETY")

    /** Generated content failed safety check. */
    val GENERATED_CONTENT_SAFETY = TurnCompleteReason("GENERATED_CONTENT_SAFETY")

    /** Generated audio failed safety check. */
    val GENERATED_AUDIO_SAFETY = TurnCompleteReason("GENERATED_AUDIO_SAFETY")

    /** Generated video failed safety check. */
    val GENERATED_VIDEO_SAFETY = TurnCompleteReason("GENERATED_VIDEO_SAFETY")

    /** Generated content is prohibited. */
    val GENERATED_CONTENT_PROHIBITED = TurnCompleteReason("GENERATED_CONTENT_PROHIBITED")

    /** Generated content matched blocklist. */
    val GENERATED_CONTENT_BLOCKLIST = TurnCompleteReason("GENERATED_CONTENT_BLOCKLIST")

    /** Generated image is prohibited. */
    val GENERATED_IMAGE_PROHIBITED = TurnCompleteReason("GENERATED_IMAGE_PROHIBITED")

    /** Generated image contains celebrity. */
    val GENERATED_IMAGE_CELEBRITY = TurnCompleteReason("GENERATED_IMAGE_CELEBRITY")

    /** Generated image contains prominent people detected by rewriter. */
    val GENERATED_IMAGE_PROMINENT_PEOPLE_DETECTED_BY_REWRITER =
      TurnCompleteReason("GENERATED_IMAGE_PROMINENT_PEOPLE_DETECTED_BY_REWRITER")

    /** Generated image contains identifiable people. */
    val GENERATED_IMAGE_IDENTIFIABLE_PEOPLE =
      TurnCompleteReason("GENERATED_IMAGE_IDENTIFIABLE_PEOPLE")

    /** Generated image contains minors. */
    val GENERATED_IMAGE_MINORS = TurnCompleteReason("GENERATED_IMAGE_MINORS")

    /** Generated image contains IP violation. */
    val OUTPUT_IMAGE_IP_PROHIBITED = TurnCompleteReason("OUTPUT_IMAGE_IP_PROHIBITED")

    /** Other generated content issue. */
    val GENERATED_OTHER = TurnCompleteReason("GENERATED_OTHER")

    /** Max regeneration attempts reached. */
    val MAX_REGENERATION_REACHED = TurnCompleteReason("MAX_REGENERATION_REACHED")
  }
}
